# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('flat_No', models.CharField(max_length=5)),
                ('flat_99', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
                ('entrance_No', models.IntegerField(default=0)),
                ('floor_No', models.IntegerField(default=0)),
                ('room1_S', models.FloatField(default=0)),
                ('room2_S', models.FloatField(default=0)),
                ('room3_S', models.FloatField(default=0)),
                ('kitchen_S', models.FloatField(default=0)),
                ('toilet_S', models.FloatField(default=0)),
                ('bathroom_S', models.FloatField(default=0)),
                ('larder1_S', models.FloatField(default=0)),
                ('larder2_S', models.FloatField(default=0)),
                ('corridor_S', models.FloatField(default=0)),
                ('loggia_S', models.FloatField(default=0)),
                ('s_BTI', models.FloatField(default=0)),
                ('s0_BTI', models.FloatField(default=0)),
                ('s_plan', models.FloatField(default=0)),
                ('s0_plan', models.FloatField(default=0)),
                ('bti_plan', models.FloatField(default=0)),
                ('deviation', models.FloatField(default=0)),
                ('note', models.FloatField(default=0)),
                ('listing', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('flat_99', models.IntegerField(default=0)),
                ('person_ID', models.IntegerField(default=0)),
                ('coop_member', models.BooleanField(default=False)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('if_queue', models.BooleanField(default=False)),
                ('if_retaired', models.BooleanField(default=False)),
                ('if_ZEK', models.BooleanField(default=False)),
                ('old_family_rel', models.CharField(default='', max_length=100)),
                ('on_queue_with', models.BooleanField(default=False)),
                ('will_living', models.BooleanField(default=False)),
                ('family_rel', models.CharField(default='', max_length=20)),
                ('birthday', models.DateField(default=datetime.date(1900, 1, 1))),
                ('year_of_birth', models.IntegerField(default=0)),
                ('queue_in', models.CharField(default='', max_length=100)),
                ('town_sertif_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('flat_reg_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('flat_reg_No', models.IntegerField(default=0)),
                ('flat_privil_reg_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('flat_privil_reg_No', models.IntegerField(default=0)),
                ('flat_privil_reg_like', models.CharField(default='', max_length=100)),
                ('coop_reg_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('coop_reg_No', models.IntegerField(default=0)),
                ('coop_privil_reg_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('coop_privil_reg_No', models.IntegerField(default=0)),
                ('coop_privil_reg_like', models.CharField(default='', max_length=100)),
                ('member_pib', models.CharField(default='', max_length=100)),
                ('telephone_old', models.CharField(default='', max_length=20)),
                ('experience_from', models.IntegerField(default=0)),
                ('queue_from', models.IntegerField(default=0)),
                ('privilege', models.CharField(default='', max_length=100)),
                ('professor', models.BooleanField(default=False)),
                ('docent', models.BooleanField(default=False)),
                ('if_second', models.BooleanField(default=False)),
                ('number_of_people', models.IntegerField(default=0)),
                ('address_old', models.CharField(default='', max_length=100)),
                ('rooms_old', models.IntegerField(default=0)),
                ('s_old', models.FloatField(default=0)),
                ('s0_old', models.FloatField(default=0)),
                ('flat_charact_old', models.CharField(default='', max_length=100)),
                ('work', models.CharField(default='', max_length=100)),
                ('faculty', models.CharField(default='', max_length=100)),
                ('work_from', models.IntegerField(default=0)),
                ('work_from_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('note', models.CharField(default='', max_length=100)),
                ('improve_house', models.BooleanField(default=False)),
                ('reg_removal', models.BooleanField(default=False)),
                ('in_Lviv_from', models.CharField(default='', max_length=20)),
                ('control_reg_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('control_reg_No', models.IntegerField(default=0)),
                ('right_to_add_S', models.CharField(default='', max_length=100)),
                ('add_information', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=100)),
                ('if_privatized', models.BooleanField(default=False)),
                ('entry_protocol_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('exit_protocol_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('coop_control_reg_No', models.IntegerField(default=0)),
                ('info_about_missed', models.CharField(default='', max_length=100)),
                ('flat_gived_like', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
