# Список розширень файлів, для яких можливе preview:
viewable_extension_list = [
    ".jpg",
    ".pdf",
    ".txt",
]

# Список типів файлів, для яких можливе preview:
viewable_mimeType_list = [
    "text/plain",
    "text/",
]

iconPath = {
    ".123"               : ""                    ,
    ".3dml"              : ""                    ,
    ".3g2"               : ""                    ,
    ".3gp"               : ""                    ,
    ".7z"                : ""                    ,
    ".aab"               : ""                    ,
    ".aac"               : "aac.png"             ,
    ".aam"               : ""                    ,
    ".aas"               : ""                    ,
    ".abw"               : ""                    ,
    ".ac"                : ""                    ,
    ".acc"               : ""                    ,
    ".ace"               : ""                    ,
    ".acu"               : ""                    ,
    ".adp"               : ""                    ,
    ".aep"               : ""                    ,
    ".afp"               : ""                    ,
    ".ahead"             : ""                    ,
    ".ai"                : "ai.png"              ,
    ".aif"               : ""                    ,
    ".air"               : ""                    ,
    ".ait"               : ""                    ,
    ".ami"               : ""                    ,
    ".apk"               : ""                    ,
    ".application"       : ""                    ,
    ".apr"               : ""                    ,
    ".asf"               : ""                    ,
    ".aso"               : ""                    ,
    ".atc"               : ""                    ,
    ".atom"              : ""                    ,
    ".atomcat"           : ""                    ,
    ".atomsvc"           : ""                    ,
    ".atx"               : ""                    ,
    ".au"                : ""                    ,
    ".avi"               : "avi.png"             ,
    ".aw"                : ""                    ,
    ".azf"               : ""                    ,
    ".azs"               : ""                    ,
    ".azw"               : ""                    ,
    ".bcpio"             : ""                    ,
    ".bdf"               : ""                    ,
    ".bdm"               : ""                    ,
    ".bed"               : ""                    ,
    ".bh2"               : ""                    ,
    ".bin"               : ""                    ,
    ".bmi"               : ""                    ,
    ".bmp"               : "bmp.png"             ,
    ".box"               : ""                    ,
    ".btif"              : ""                    ,
    ".bz"                : ""                    ,
    ".bz2"               : ""                    ,
    ".c"                 : "c.png"               ,
    ".c11amc"            : ""                    ,
    ".c11amz"            : ""                    ,
    ".c4g"               : ""                    ,
    ".cab"               : ""                    ,
    ".car"               : ""                    ,
    ".cat"               : ""                    ,
    ".ccxml"             : ""                    ,
    ".cdbcmsg"           : ""                    ,
    ".cdkey"             : ""                    ,
    ".cdmia"             : ""                    ,
    ".cdmic"             : ""                    ,
    ".cdmid"             : ""                    ,
    ".cdmio"             : ""                    ,
    ".cdmiq"             : ""                    ,
    ".cdx"               : ""                    ,
    ".cdxml"             : ""                    ,
    ".cdy"               : ""                    ,
    ".cer"               : ""                    ,
    ".cgm"               : ""                    ,
    ".chat"              : ""                    ,
    ".chm"               : ""                    ,
    ".chrt"              : ""                    ,
    ".cif"               : ""                    ,
    ".cii"               : ""                    ,
    ".cil"               : ""                    ,
    ".cla"               : ""                    ,
    ".class"             : ""                    ,
    ".clkk"              : ""                    ,
    ".clkp"              : ""                    ,
    ".clkt"              : ""                    ,
    ".clkw"              : ""                    ,
    ".clkx"              : ""                    ,
    ".clp"               : ""                    ,
    ".cmc"               : ""                    ,
    ".cmdf"              : ""                    ,
    ".cml"               : ""                    ,
    ".cmp"               : ""                    ,
    ".cmx"               : ""                    ,
    ".cod"               : ""                    ,
    ".cpio"              : ""                    ,
    ".cpt"               : ""                    ,
    ".crd"               : ""                    ,
    ".crl"               : ""                    ,
    ".cryptonote"        : ""                    ,
    ".csh"               : ""                    ,
    ".csml"              : ""                    ,
    ".csp"               : ""                    ,
    ".css"               : "css.png"             ,
    ".csv"               : ""                    ,
    ".cu"                : ""                    ,
    ".curl"              : ""                    ,
    ".cww"               : ""                    ,
    ".dae"               : ""                    ,
    ".daf"               : ""                    ,
    ".davmount"          : ""                    ,
    ".dcurl"             : ""                    ,
    ".dd2"               : ""                    ,
    ".ddd"               : ""                    ,
    ".deb"               : ""                    ,
    ".der"               : ""                    ,
    ".dfac"              : ""                    ,
    ".dir"               : ""                    ,
    ".dis"               : ""                    ,
    ".djvu"              : ""                    ,
    ".dna"               : ""                    ,
    ".doc"               : "doc.png"             ,
    ".docm"              : ""                    ,
    ".docx"              : ""                    ,
    ".dotm"              : ""                    ,
    ".dotx"              : "dotx.png"            ,
    ".dp"                : ""                    ,
    ".dpg"               : ""                    ,
    ".dra"               : ""                    ,
    ".dsc"               : ""                    ,
    ".dssc"              : ""                    ,
    ".dtb"               : ""                    ,
    ".dtd"               : ""                    ,
    ".dts"               : ""                    ,
    ".dtshd"             : ""                    ,
    ".dvi"               : ""                    ,
    ".dwf"               : ""                    ,
    ".dwg"               : "dwg.png"             ,
    ".dxf"               : "dxf.png"             ,
    ".dxp"               : ""                    ,
    ".ecelp4800"         : ""                    ,
    ".ecelp7470"         : ""                    ,
    ".ecelp9600"         : ""                    ,
    ".edm"               : ""                    ,
    ".edx"               : ""                    ,
    ".efif"              : ""                    ,
    ".ei6"               : ""                    ,
    ".eml"               : ""                    ,
    ".emma"              : ""                    ,
    ".eol"               : ""                    ,
    ".eot"               : ""                    ,
    ".epub"              : ""                    ,
    ".es"                : ""                    ,
    ".es3"               : ""                    ,
    ".esf"               : ""                    ,
    ".etx"               : ""                    ,
    ".exe"               : "exe.png"             ,
    ".exi"               : ""                    ,
    ".ext"               : ""                    ,
    ".ez2"               : ""                    ,
    ".ez3"               : ""                    ,
    ".f"                 : ""                    ,
    ".f4v"               : ""                    ,
    ".fbs"               : ""                    ,
    ".fcs"               : ""                    ,
    ".fdf"               : ""                    ,
    ".fe_launch"         : ""                    ,
    ".fg5"               : ""                    ,
    ".fh"                : ""                    ,
    ".fig"               : ""                    ,
    ".fli"               : ""                    ,
    ".flo"               : ""                    ,
    ".flv"               : "flv.png"             ,
    ".flw"               : ""                    ,
    ".flx"               : ""                    ,
    ".fly"               : ""                    ,
    ".fm"                : ""                    ,
    ".fnc"               : ""                    ,
    ".fpx"               : ""                    ,
    ".fsc"               : ""                    ,
    ".fst"               : ""                    ,
    ".ftc"               : ""                    ,
    ".fti"               : ""                    ,
    ".fvt"               : ""                    ,
    ".fxp"               : ""                    ,
    ".fzs"               : ""                    ,
    ".g2w"               : ""                    ,
    ".g3"                : ""                    ,
    ".g3w"               : ""                    ,
    ".gac"               : ""                    ,
    ".gdl"               : ""                    ,
    ".geo"               : ""                    ,
    ".gex"               : ""                    ,
    ".ggb"               : ""                    ,
    ".ggt"               : ""                    ,
    ".ghf"               : ""                    ,
    ".gif"               : "gif.png"             ,
    ".gim"               : ""                    ,
    ".gmx"               : ""                    ,
    ".gnumeric"          : ""                    ,
    ".gph"               : ""                    ,
    ".gqf"               : ""                    ,
    ".gram"              : ""                    ,
    ".grv"               : ""                    ,
    ".grxml"             : ""                    ,
    ".gsf"               : ""                    ,
    ".gtar"              : ""                    ,
    ".gtm"               : ""                    ,
    ".gtw"               : ""                    ,
    ".gv"                : ""                    ,
    ".gxt"               : ""                    ,
    ".h261"              : ""                    ,
    ".h263"              : ""                    ,
    ".h264"              : ""                    ,
    ".hal"               : ""                    ,
    ".hbci"              : ""                    ,
    ".hdf"               : ""                    ,
    ".hlp"               : ""                    ,
    ".hpgl"              : ""                    ,
    ".hpid"              : ""                    ,
    ".hps"               : ""                    ,
    ".hqx"               : ""                    ,
    ".htke"              : ""                    ,
    ".html"              : "html.png"            ,
    ".hvd"               : ""                    ,
    ".hvp"               : ""                    ,
    ".hvs"               : ""                    ,
    ".i2g"               : ""                    ,
    ".icc"               : ""                    ,
    ".ice"               : ""                    ,
    ".ico"               : ""                    ,
    ".ics"               : "ics.png"             ,
    ".ief"               : ""                    ,
    ".ifm"               : ""                    ,
    ".igl"               : ""                    ,
    ".igm"               : ""                    ,
    ".igs"               : ""                    ,
    ".igx"               : ""                    ,
    ".iif"               : ""                    ,
    ".imp"               : ""                    ,
    ".ims"               : ""                    ,
    ".ipfix"             : ""                    ,
    ".ipk"               : ""                    ,
    ".irm"               : ""                    ,
    ".irp"               : ""                    ,
    ".itp"               : ""                    ,
    ".ivp"               : ""                    ,
    ".ivu"               : ""                    ,
    ".jad"               : ""                    ,
    ".jam"               : ""                    ,
    ".jar"               : ""                    ,
    ".java"              : "java.png"            ,
    ".jisp"              : ""                    ,
    ".jlt"               : ""                    ,
    ".jnlp"              : ""                    ,
    ".joda"              : ""                    ,
    ".jpeg"              : ""                    ,
    ".jpg"               : "jpg.png"             ,
    ".jpgv"              : ""                    ,
    ".jpm"               : ""                    ,
    ".js"                : "js.png"              ,
    ".json"              : ""                    ,
    ".karbon"            : ""                    ,
    ".kfo"               : ""                    ,
    ".kia"               : ""                    ,
    ".kml"               : ""                    ,
    ".kmz"               : ""                    ,
    ".kne"               : ""                    ,
    ".kon"               : ""                    ,
    ".kpr"               : ""                    ,
    ".ksp"               : ""                    ,
    ".ktx"               : ""                    ,
    ".ktz"               : ""                    ,
    ".kwd"               : ""                    ,
    ".lasxml"            : ""                    ,
    ".latex"             : ""                    ,
    ".lbd"               : ""                    ,
    ".lbe"               : ""                    ,
    ".les"               : ""                    ,
    ".link66"            : ""                    ,
    ".lrm"               : ""                    ,
    ".ltf"               : ""                    ,
    ".lvp"               : ""                    ,
    ".lwp"               : ""                    ,
    ".m21"               : ""                    ,
    ".m3u"               : ""                    ,
    ".m3u8"              : ""                    ,
    ".m4v"               : ""                    ,
    ".ma"                : ""                    ,
    ".mads"              : ""                    ,
    ".mag"               : ""                    ,
    ".mathml"            : ""                    ,
    ".mbk"               : ""                    ,
    ".mbox"              : ""                    ,
    ".mc1"               : ""                    ,
    ".mcd"               : ""                    ,
    ".mcurl"             : ""                    ,
    ".mdb"               : ""                    ,
    ".mdi"               : ""                    ,
    ".meta4"             : ""                    ,
    ".mets"              : ""                    ,
    ".mfm"               : ""                    ,
    ".mgp"               : ""                    ,
    ".mgz"               : ""                    ,
    ".mid"               : "mid.png"             ,
    ".mif"               : ""                    ,
    ".mj2"               : ""                    ,
    ".mlp"               : ""                    ,
    ".mmd"               : ""                    ,
    ".mmf"               : ""                    ,
    ".mmr"               : ""                    ,
    ".mny"               : ""                    ,
    ".mods"              : ""                    ,
    ".movie"             : ""                    ,
    ".mp4"               : "mp4.png"             ,
    ".mp4a"              : ""                    ,
    ".mpc"               : ""                    ,
    ".mpeg"              : ""                    ,
    ".mpga"              : ""                    ,
    ".mpkg"              : ""                    ,
    ".mpm"               : ""                    ,
    ".mpn"               : ""                    ,
    ".mpp"               : ""                    ,
    ".mpy"               : ""                    ,
    ".mqy"               : ""                    ,
    ".mrc"               : ""                    ,
    ".mrcx"              : ""                    ,
    ".mscml"             : ""                    ,
    ".mseq"              : ""                    ,
    ".msf"               : ""                    ,
    ".msh"               : ""                    ,
    ".msl"               : ""                    ,
    ".msty"              : ""                    ,
    ".mts"               : ""                    ,
    ".mus"               : ""                    ,
    ".musicxml"          : ""                    ,
    ".mvb"               : ""                    ,
    ".mwf"               : ""                    ,
    ".mxf"               : ""                    ,
    ".mxl"               : ""                    ,
    ".mxml"              : ""                    ,
    ".mxs"               : ""                    ,
    ".mxu"               : ""                    ,
    ".n-gage"            : ""                    ,
    ".n3"                : ""                    ,
    ".nbp"               : ""                    ,
    ".nc"                : ""                    ,
    ".ncx"               : ""                    ,
    ".ngdat"             : ""                    ,
    ".nlu"               : ""                    ,
    ".nml"               : ""                    ,
    ".nnd"               : ""                    ,
    ".nns"               : ""                    ,
    ".nnw"               : ""                    ,
    ".npx"               : ""                    ,
    ".nsf"               : ""                    ,
    ".oa2"               : ""                    ,
    ".oa3"               : ""                    ,
    ".oas"               : ""                    ,
    ".obd"               : ""                    ,
    ".oda"               : ""                    ,
    ".odb"               : ""                    ,
    ".odc"               : ""                    ,
    ".odf"               : "odf.png"             ,
    ".odft"              : ""                    ,
    ".odg"               : ""                    ,
    ".odi"               : ""                    ,
    ".odm"               : ""                    ,
    ".odp"               : ""                    ,
    ".ods"               : "ods.png"             ,
    ".odt"               : "odt.png"             ,
    ".oga"               : ""                    ,
    ".ogv"               : ""                    ,
    ".ogx"               : ""                    ,
    ".onetoc"            : ""                    ,
    ".opf"               : ""                    ,
    ".org"               : ""                    ,
    ".osf"               : ""                    ,
    ".osfpvg"            : ""                    ,
    ".otc"               : ""                    ,
    ".otf"               : ""                    ,
    ".otg"               : ""                    ,
    ".oth"               : ""                    ,
    ".oti"               : ""                    ,
    ".otp"               : "otp.png"             ,
    ".ots"               : "ots.png"             ,
    ".ott"               : "ott.png"             ,
    ".oxt"               : ""                    ,
    ".p"                 : ""                    ,
    ".p10"               : ""                    ,
    ".p12"               : ""                    ,
    ".p7b"               : ""                    ,
    ".p7m"               : ""                    ,
    ".p7r"               : ""                    ,
    ".p7s"               : ""                    ,
    ".p8"                : ""                    ,
    ".par"               : ""                    ,
    ".paw"               : ""                    ,
    ".pbd"               : ""                    ,
    ".pbm"               : ""                    ,
    ".pcf"               : ""                    ,
    ".pcl"               : ""                    ,
    ".pclxl"             : ""                    ,
    ".pcurl"             : ""                    ,
    ".pcx"               : ""                    ,
    ".pdb"               : ""                    ,
    ".pdf"               : "pdf.png"             ,
    ".pfa"               : ""                    ,
    ".pfr"               : ""                    ,
    ".pgm"               : ""                    ,
    ".pgn"               : ""                    ,
    ".pgp"               : ""                    ,
    ".pic"               : ""                    ,
    ".pki"               : ""                    ,
    ".pkipath"           : ""                    ,
    ".plb"               : ""                    ,
    ".plc"               : ""                    ,
    ".plf"               : ""                    ,
    ".pls"               : ""                    ,
    ".pml"               : ""                    ,
    ".png"               : "png.png"             ,
    ".pnm"               : ""                    ,
    ".portpkg"           : ""                    ,
    ".potm"              : ""                    ,
    ".potx"              : ""                    ,
    ".ppam"              : ""                    ,
    ".ppd"               : ""                    ,
    ".ppm"               : ""                    ,
    ".ppsm"              : ""                    ,
    ".ppsx"              : ""                    ,
    ".ppt"               : "ppt.png"             ,
    ".pptm"              : ""                    ,
    ".pptx"              : ""                    ,
    ".prc"               : ""                    ,
    ".pre"               : ""                    ,
    ".prf"               : ""                    ,
    ".psb"               : ""                    ,
    ".psd"               : "psd.png"             ,
    ".psf"               : ""                    ,
    ".pskcxml"           : ""                    ,
    ".ptid"              : ""                    ,
    ".pub"               : ""                    ,
    ".pvb"               : ""                    ,
    ".pwn"               : ""                    ,
    ".pya"               : ""                    ,
    ".pyv"               : ""                    ,
    ".qam"               : ""                    ,
    ".qbo"               : ""                    ,
    ".qfx"               : ""                    ,
    ".qps"               : ""                    ,
    ".qt"                : "qt.png"              ,
    ".qxd"               : ""                    ,
    ".ram"               : ""                    ,
    ".rar"               : "rar.png"             ,
    ".ras"               : ""                    ,
    ".rcprofile"         : ""                    ,
    ".rdf"               : ""                    ,
    ".rdz"               : ""                    ,
    ".rep"               : ""                    ,
    ".res"               : ""                    ,
    ".rgb"               : ""                    ,
    ".rif"               : ""                    ,
    ".rip"               : ""                    ,
    ".rl"                : ""                    ,
    ".rlc"               : ""                    ,
    ".rld"               : ""                    ,
    ".rm"                : ""                    ,
    ".rmp"               : ""                    ,
    ".rms"               : ""                    ,
    ".rnc"               : ""                    ,
    ".rp9"               : ""                    ,
    ".rpss"              : ""                    ,
    ".rpst"              : ""                    ,
    ".rq"                : ""                    ,
    ".rs"                : ""                    ,
    ".rsd"               : ""                    ,
    ".rss"               : ""                    ,
    ".rtf"               : "rtf.png"             ,
    ".rtx"               : ""                    ,
    ".s"                 : ""                    ,
    ".saf"               : ""                    ,
    ".sbml"              : ""                    ,
    ".sc"                : ""                    ,
    ".scd"               : ""                    ,
    ".scm"               : ""                    ,
    ".scq"               : ""                    ,
    ".scs"               : ""                    ,
    ".scurl"             : ""                    ,
    ".sda"               : ""                    ,
    ".sdc"               : ""                    ,
    ".sdd"               : ""                    ,
    ".sdkm"              : ""                    ,
    ".sdp"               : ""                    ,
    ".sdw"               : ""                    ,
    ".see"               : ""                    ,
    ".seed"              : ""                    ,
    ".sema"              : ""                    ,
    ".semd"              : ""                    ,
    ".semf"              : ""                    ,
    ".ser"               : ""                    ,
    ".setpay"            : ""                    ,
    ".setreg"            : ""                    ,
    ".sfd-hdstx"         : ""                    ,
    ".sfs"               : ""                    ,
    ".sgl"               : ""                    ,
    ".sgml"              : ""                    ,
    ".sh"                : ""                    ,
    ".shar"              : ""                    ,
    ".shf"               : ""                    ,
    ".sis"               : ""                    ,
    ".sit"               : ""                    ,
    ".sitx"              : ""                    ,
    ".skp"               : ""                    ,
    ".sldm"              : ""                    ,
    ".sldx"              : ""                    ,
    ".slt"               : ""                    ,
    ".sm"                : ""                    ,
    ".smf"               : ""                    ,
    ".smi"               : ""                    ,
    ".snf"               : ""                    ,
    ".spf"               : ""                    ,
    ".spl"               : ""                    ,
    ".spot"              : ""                    ,
    ".spp"               : ""                    ,
    ".spq"               : ""                    ,
    ".src"               : ""                    ,
    ".sru"               : ""                    ,
    ".srx"               : ""                    ,
    ".sse"               : ""                    ,
    ".ssf"               : ""                    ,
    ".ssml"              : ""                    ,
    ".st"                : ""                    ,
    ".stc"               : ""                    ,
    ".std"               : ""                    ,
    ".stf"               : ""                    ,
    ".sti"               : ""                    ,
    ".stk"               : ""                    ,
    ".stl"               : ""                    ,
    ".str"               : ""                    ,
    ".stw"               : ""                    ,
    ".sub"               : ""                    ,
    ".sus"               : ""                    ,
    ".sv4cpio"           : ""                    ,
    ".sv4crc"            : ""                    ,
    ".svc"               : ""                    ,
    ".svd"               : ""                    ,
    ".svg"               : ""                    ,
    ".swf"               : ""                    ,
    ".swi"               : ""                    ,
    ".sxc"               : ""                    ,
    ".sxd"               : ""                    ,
    ".sxg"               : ""                    ,
    ".sxi"               : ""                    ,
    ".sxm"               : ""                    ,
    ".sxw"               : ""                    ,
    ".t"                 : ""                    ,
    ".tao"               : ""                    ,
    ".tar"               : ""                    ,
    ".tcap"              : ""                    ,
    ".tcl"               : ""                    ,
    ".teacher"           : ""                    ,
    ".tei"               : ""                    ,
    ".tex"               : ""                    ,
    ".texinfo"           : ""                    ,
    ".tfi"               : ""                    ,
    ".tfm"               : ""                    ,
    ".thmx"              : ""                    ,
    ".tiff"              : "tiff.png"            ,
    ".tmo"               : ""                    ,
    ".torrent"           : ""                    ,
    ".tpl"               : ""                    ,
    ".tpt"               : ""                    ,
    ".tra"               : ""                    ,
    ".trm"               : ""                    ,
    ".tsd"               : ""                    ,
    ".tsv"               : ""                    ,
    ".ttf"               : ""                    ,
    ".ttl"               : ""                    ,
    ".twd"               : ""                    ,
    ".txd"               : ""                    ,
    ".txf"               : ""                    ,
    ".txt"               : "txt.png"             ,
    ".ufd"               : ""                    ,
    ".umj"               : ""                    ,
    ".unityweb"          : ""                    ,
    ".uoml"              : ""                    ,
    ".uri"               : ""                    ,
    ".ustar"             : ""                    ,
    ".utz"               : ""                    ,
    ".uu"                : ""                    ,
    ".uva"               : ""                    ,
    ".uvh"               : ""                    ,
    ".uvi"               : ""                    ,
    ".uvm"               : ""                    ,
    ".uvp"               : ""                    ,
    ".uvs"               : ""                    ,
    ".uvu"               : ""                    ,
    ".uvv"               : ""                    ,
    ".vcd"               : ""                    ,
    ".vcf"               : ""                    ,
    ".vcg"               : ""                    ,
    ".vcs"               : ""                    ,
    ".vcx"               : ""                    ,
    ".vis"               : ""                    ,
    ".viv"               : ""                    ,
    ".vsd"               : ""                    ,
    ".vsf"               : ""                    ,
    ".vtu"               : ""                    ,
    ".vxml"              : ""                    ,
    ".wad"               : ""                    ,
    ".wav"               : "wav.png"             ,
    ".wax"               : ""                    ,
    ".wbmp"              : ""                    ,
    ".wbs"               : ""                    ,
    ".wbxml"             : ""                    ,
    ".weba"              : ""                    ,
    ".webm"              : ""                    ,
    ".webp"              : ""                    ,
    ".wg"                : ""                    ,
    ".wgt"               : ""                    ,
    ".wm"                : ""                    ,
    ".wma"               : ""                    ,
    ".wmd"               : ""                    ,
    ".wmf"               : ""                    ,
    ".wml"               : ""                    ,
    ".wmlc"              : ""                    ,
    ".wmls"              : ""                    ,
    ".wmlsc"             : ""                    ,
    ".wmv"               : ""                    ,
    ".wmx"               : ""                    ,
    ".wmz"               : ""                    ,
    ".woff"              : ""                    ,
    ".wpd"               : ""                    ,
    ".wpl"               : ""                    ,
    ".wps"               : ""                    ,
    ".wqd"               : ""                    ,
    ".wri"               : ""                    ,
    ".wrl"               : ""                    ,
    ".wsdl"              : ""                    ,
    ".wspolicy"          : ""                    ,
    ".wtb"               : ""                    ,
    ".wvx"               : ""                    ,
    ".x3d"               : ""                    ,
    ".xap"               : ""                    ,
    ".xar"               : ""                    ,
    ".xbap"              : ""                    ,
    ".xbd"               : ""                    ,
    ".xbm"               : ""                    ,
    ".xdf"               : ""                    ,
    ".xdm"               : ""                    ,
    ".xdp"               : ""                    ,
    ".xdssc"             : ""                    ,
    ".xdw"               : ""                    ,
    ".xenc"              : ""                    ,
    ".xer"               : ""                    ,
    ".xfdf"              : ""                    ,
    ".xfdl"              : ""                    ,
    ".xhtml"             : ""                    ,
    ".xif"               : ""                    ,
    ".xlam"              : ""                    ,
    ".xls"               : "xls.png"             ,
    ".xlsb"              : ""                    ,
    ".xlsm"              : ""                    ,
    ".xlsx"              : "xlsx.png"            ,
    ".xltm"              : ""                    ,
    ".xltx"              : ""                    ,
    ".xml"               : "xml.png"             ,
    ".xo"                : ""                    ,
    ".xop"               : ""                    ,
    ".xpi"               : ""                    ,
    ".xpm"               : ""                    ,
    ".xpr"               : ""                    ,
    ".xps"               : ""                    ,
    ".xpw"               : ""                    ,
    ".xslt"              : ""                    ,
    ".xsm"               : ""                    ,
    ".xspf"              : ""                    ,
    ".xul"               : ""                    ,
    ".xwd"               : ""                    ,
    ".xyz"               : ""                    ,
    ".yaml"              : ""                    ,
    ".yang"              : ""                    ,
    ".yin"               : ""                    ,
    ".zaz"               : ""                    ,
    ".zip"               : "zip.png"             ,
    ".zir"               : ""                    ,
    ".zmm"               : ""                    ,
}


if __name__ == "__main__":
    """
    iconlist - список назв файлів з іконками.
    Щоб знайти їм відповідність у словнику iconPath,
    потрібно запустити new_iconPath(). Буде надруковано
    список, який можна просто скопіювати в iconPath між {} .
    """
    iconlist = [
            "aac.png"       ,
            "ai.png"        ,
            "aiff.png"      ,
            "avi.png"       ,
            "bmp.png"       ,
            "c.png"     ,
            "cpp.png"       ,
            "css.png"       ,
            "dat.png"       ,
            "dmg.png"       ,
            "doc.png"       ,
            "dotx.png"      ,
            "dwg.png"       ,
            "dxf.png"       ,
            "eps.png"       ,
            "exe.png"       ,
            "flv.png"       ,
            "gif.png"       ,
            "h.png"     ,
            "hpp.png"       ,
            "html.png"      ,
            "ics.png"       ,
            "iso.png"       ,
            "java.png"      ,
            "jpg.png"       ,
            "js.png"        ,
            "key.png"       ,
            "less.png"      ,
            "mid.png"       ,
            "mp3.png"       ,
            "mp4.png"       ,
            "mpg.png"       ,
            "odf.png"       ,
            "ods.png"       ,
            "odt.png"       ,
            "otp.png"       ,
            "ots.png"       ,
            "ott.png"       ,
            "pdf.png"       ,
            "php.png"       ,
            "png.png"       ,
            "ppt.png"       ,
            "psd.png"       ,
            "py.png"        ,
            "qt.png"        ,
            "rar.png"       ,
            "rb.png"        ,
            "rtf.png"       ,
            "sass.png"      ,
            "scss.png"      ,
            "sql.png"       ,
            "tga.png"       ,
            "tgz.png"       ,
            "tiff.png"      ,
            "txt.png"       ,
            "wav.png"       ,
            "xls.png"       ,
            "xlsx.png"      ,
            "xml.png"       ,
            "yml.png"       ,
            "zip.png"       ,
            "_blank.png"        ,
            "_page.png"     ,
            ]


    import os.path

    def new_iconPath():

        unfounded = []
        for fileName in iconlist:
            (name, ext) = os.path.splitext(fileName)
            dotname = '.' + name
            print('%10s %-10s' % (fileName, dotname))
            if dotname in iconPath:
                iconPath[dotname] = fileName
            else:
                unfounded.append(fileName)

        print('New iconPath:----------------------------------------')
        for k in sorted(iconPath):
            print('%-10s %-10s' % (k, iconPath[k]))
        print('Unfounded:----------------------------------------')
        for f in unfounded:
            print(f)
        print('all icons:', len(iconlist))
        print('unfounded:', len(unfounded))

        def wrap(s):
            w = '"%s"' % s
            return w
        pattern = '    %-20s : %-20s  ,'
        print('New iconPath:----------------------------------------')
        for k in sorted(iconPath):
            print(pattern % (wrap(k), wrap(iconPath[k])))

    new_iconPath()
